mamba create --name cellphonedb python=3.8
conda acivate cellphonedb
pip install cellphonedb==3.1.0


mamba create --name cellphonedb python=3.8 r-base rpy2 -y && conda activate cellphonedb && pip install cellphonedb==3.1.0


devtools::install_github("saezlab/OmnipathR@v3.7.0")

above needs install bioconda::bioconductor-genomeinfodbdata

if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("GenomeInfoDbData")



NN

devtools::install_github("saeyslab/nichenetr")